spring:
    profiles:
        active: dev   # 현재 파일이 개발환경에서 실행중이다.
        include: secret # 현재 active로 지정된 dev파일 외에 application-secret.yml 파일도 찾아서 파일을 설정하는데 보통 secret.yml은 gitIgnore에 담아서 적용함. 

    jpa:
        hibernate:
            ddl-auto: create

        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
            
logging:
    level:
        root: info
