server:
    port: 8080
spring:
    output:
        ansi:
            enabled: always

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 1111
        url: jdbc:mysql://localhost:3306/my_db

custom:
    filedDirPath: /usr/work